# Reddit Content Crawler Configuration

# Subreddits to crawl
subreddits:
  - AskReddit
  # - news
  # - worldnews

# Crawling parameters
crawling:
  listing: "controversial"          # Options: "new", "top", "hot", "rising" "best", "controversial"
  timefilter: "hour"       # For top listing: "hour", "day", "week", "month", "year", "all"
  post_limit: null         # Number of posts to crawl per subreddit (null for unlimited)
  post_sleep: 0.4         # Delay between posts to avoid rate limiting

# Language filtering
language:
  # Target language for filtering (ISO 639-1 code, e.g., "en", "es", "fr", "el" for Greek)
  # Set to null or empty string to disable language filtering
  target_language: en  # "el" for Greek, "en" for English, etc.
  
  # Comment-level filtering
  filter_comments_by_language: true
  
  # Post-level filtering  
  require_title_language: true
  require_op_language: false
  
  # Minimum ratio of target language characters in title (for languages with unique scripts)
  # Only used when target_language is set and the language has a unique character set
  title_min_language_ratio: 0.30

# Output settings
output:
  base_dir: "reddit_dump"
  buffer_size: 2000       # Write to disk every N comments

# Reddit API credentials (set via environment variables)
reddit_api:
  client_id_env: "REDDIT_CLIENT_ID"
  client_secret_env: "REDDIT_CLIENT_SECRET"
  user_agent_env: "REDDIT_USER_AGENT"
  request_timeout: 30

# Default user agent if not set in environment
default_user_agent: "reddit-crawler:v2.0 (by u/YOURUSER)"
